package apps.window.referencewindow;

import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.awt.event.ItemEvent;
import java.awt.event.ItemListener;
import java.awt.event.MouseEvent;
import java.awt.event.WindowAdapter;
import java.awt.event.WindowEvent;
import java.rmi.RemoteException;
import java.util.Iterator;
import java.util.Vector;

import javax.swing.DefaultListModel;
import javax.swing.table.DefaultTableModel;

import util.commonUTIL;
import apps.window.utilwindow.JDialogBoxForChoice;
import apps.window.utilwindow.JDialogTable;
import beans.LegalEntity;
import beans.Sdi;
import beans.StartUPData;
import dsServices.RemoteReferenceData;
import dsServices.ServerConnectionUtil;

public class SDI1Window  extends javax.swing.JPanel {

	public static  ServerConnectionUtil de = null;
	 DefaultTableModel attributeModel = null;
	 SDITab1 browseTab = null;
	int leID = 0;
	int poID =0;
	int agentID =0;
	RemoteReferenceData remoteBORef;
	public  DefaultTableModel model = null;
	DefaultListModel currencyList = new DefaultListModel();
	javax.swing.DefaultComboBoxModel  payRec = new javax.swing.DefaultComboBoxModel();
	javax.swing.DefaultComboBoxModel method = new javax.swing.DefaultComboBoxModel();
	javax.swing.DefaultComboBoxModel cashMethod = new javax.swing.DefaultComboBoxModel();
	javax.swing.DefaultComboBoxModel lecontacts = new javax.swing.DefaultComboBoxModel();
	 final  JDialogTable showLE = null;
	
	String s [] = {"id","LegalEntityName"};
	DefaultTableModel tradertablemodel = new DefaultTableModel(s,0);
	String po [] = {"id","POName"};
	DefaultTableModel potablemodel = new DefaultTableModel(po,0);
	String agent [] = {"id","AgentName"};
	DefaultTableModel agenttablemodel = new DefaultTableModel(agent,0);
	 javax.swing.DefaultComboBoxModel productTypeCombox = new javax.swing.DefaultComboBoxModel();
    /** Creates new form SDIFrame */
    public SDI1Window() {
        initComponents();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">
    private void initComponents() {
    	Vector roles = null;
    	de =ServerConnectionUtil.connect("localhost", 1099,commonUTIL.getServerIP() );
      	 try {
      		 remoteBORef = (RemoteReferenceData) de.getRMIService("ReferenceData");
      		  roles = (Vector) remoteBORef.getStartUPData("Roles");
   	  	 } catch (RemoteException e) {
   			e.printStackTrace();
   	}
        jTabbedPane2 = new javax.swing.JTabbedPane();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jTextField2 = new  javax.swing.JComboBox(); 
        jLabel3 = new javax.swing.JLabel();
        jTextField3 = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jTextField4 = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jTextField5 = new javax.swing.JComboBox(); 
        jLabel6 = new javax.swing.JLabel();
        jTextField6 = new  javax.swing.JComboBox(); 
        partyButton = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jTextField1 = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jTextField7 = new  javax.swing.JComboBox(); 
        jLabel8 = new javax.swing.JLabel();
        jTextField8 = new javax.swing.JComboBox();
        jLabel9 = new javax.swing.JLabel();
        jTextField9 = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        jComboBox1 = new javax.swing.JComboBox();
        jLabel11 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        jLabel12 = new javax.swing.JLabel();
        jTextField11 = new javax.swing.JTextField();
        jButton7 = new javax.swing.JButton();
        jLabel13 = new javax.swing.JLabel();
        jTextField12 = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();
        jTextField13 = new javax.swing.JComboBox();
        jLabel15 = new javax.swing.JLabel();
        jTextField14 = new javax.swing.JTextField();
        deleteButton = new javax.swing.JButton();
        saveButton = new javax.swing.JButton();
        saveAsNewButton = new javax.swing.JButton();
        newButton = new javax.swing.JButton();
        jButton8 = new javax.swing.JButton();
        
        jTextField1.setEditable(false);
        jLabel1.setText("SD id");
    	getMasterDataOnComboBox(productTypeCombox, "ProductType");
    	getMasterDataOnComboBox(lecontacts,"LEContacts");
        jComboBox1.setModel(productTypeCombox);
       
        jLabel2.setText("ROLE");
        if(roles != null) {
        	Iterator its = roles.iterator();
        	while(its.hasNext()) {
        		StartUPData role = (StartUPData) its.next();
        		jTextField2.addItem(role.getName());
        		
        	}
        	jTextField2.setSelectedIndex(1);
        }
        
        
        getLEDataCombo1(tradertablemodel,"CounterParty");
        final  JDialogTable showLE = new JDialogTable(tradertablemodel);
        showLE.setLocationRelativeTo(this);
        
        
        jTextField2.addItemListener( new ItemListener() {

        	@Override
        	public void itemStateChanged(ItemEvent e) {
        		// TODO Auto-generated method stub
        		
        		for(int i=0;i<tradertablemodel.getRowCount();i++) {
        			tradertablemodel.removeRow(i);
        			
        		}
        		showLE.clearRolesTables();
        	//	clearRolesTables();
        		// jTextField3.setText("          ");
        		String role = jTextField2.getSelectedItem().toString();
        		 getLEDataCombo1(tradertablemodel,role);
        		 if(role.equalsIgnoreCase("PO")) {
        			// jTextField9.setText("              ");
        			 jTextField9.setEnabled(false);
        			 jButton8.setEnabled(false);
        			 poID = -1;
        			 
        		 } else {
        			 jTextField9.setEnabled(true);
        			 jButton8.setEnabled(true);
        			 poID =0;
        			 
        		 }
        		
        	}
        	   
           });
       // jTextField2.setText("jTextField1");
        jTextField2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField2ActionPerformed(evt);
            }
        });

        jLabel3.setText("Party");

      //  jTextField3.setText("            ");
        jTextField3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField3ActionPerformed(evt);
            }
        });

        jLabel4.setText("CCY");

        jTextField4.setText("ANY          ");
        jTextField4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField4ActionPerformed(evt);
            }
        });

        jLabel5.setText("Pay/Rec");
        payRec.insertElementAt("BOTH", 0);
       // payRec.setSelectedItem(new String("BOTH"));
        payRec.insertElementAt("PAY", 1);
        payRec.insertElementAt("REC", 2);
        
        jTextField5.setModel(payRec);
        jTextField5.setSelectedIndex(0);

        jLabel6.setText("Method");
        populateMethod(method);
        jTextField6.setModel(method);

        partyButton.setText("....");
        partyButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                partyButtonActionPerformed(evt);
            }
        });

        jButton1.setText("...");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jTextField1.setText("            ");

        jLabel7.setText("Cash/Security");
        
        cashMethod.insertElementAt("BOTH", 0);
        cashMethod.insertElementAt("CASH", 1);
        cashMethod.insertElementAt("SECURITY", 2);
        cashMethod.setSelectedItem(0);
        jTextField7.setModel(cashMethod);
        jTextField7.setSelectedIndex(0);

        jLabel8.setText("Contact");

        jTextField8.setModel(lecontacts);
      
        jLabel9.setText("Prg Org");
        jTextField1.setText("0    ");
        jTextField9.setText("             ");
        jTextField9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField9ActionPerformed(evt);
            }
        });

        jLabel10.setText("Products");

     //   jComboBox1.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        jLabel11.setText("Attributes");
        String sdi [] = {"Attribue Name","Value    "};
    	DefaultTableModel sditablemodel = new DefaultTableModel(sdi,0);
        jTable1.setModel(sditablemodel);
        jScrollPane1.setViewportView(jTable1);

        jLabel12.setText("Code");

        jTextField11.setText("             ");
        jTextField11.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField11ActionPerformed(evt);
            }
        });

        jButton7.setText("jButton1");
        jButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton7ActionPerformed(evt);
            }
        });

        jLabel13.setText("A/C");

        jTextField12.setText("            ");

        jLabel14.setText("Contact");

        jTextField13.setModel(lecontacts);

        jLabel15.setText("GL");

        jTextField14.setText("           ");
        processlistchoice(currencyList,"Currency");
       	final JDialogBoxForChoice choice12 = new JDialogBoxForChoice(currencyList);
       	partyButton.addActionListener(new ActionListener() {

			@Override
			public void actionPerformed(ActionEvent e) {
				// TODO Auto-generated method stub
				
				choice12.jList3.setModel(currencyList);
				choice12.setLocationRelativeTo(choice12);
				//choice12.setSize(200,200);
				choice12.setVisible(true);
				
			}
   		
   	});
       	
        // currency textbox
       	choice12.addWindowListener(new WindowAdapter() {            
               public void windowClosing(WindowEvent e) {
                  // System.out.println("Window closing");
                   try {
                   	String ss = "";
                     Object obj [] =   choice12.getObj();
                    for(int i =0;i<obj.length;i++)
                   	 ss = ss + (String) obj[i] + ",";
                    if(ss.trim().length() > 0)
                    	jTextField4.setText(ss.substring(0, ss.length()-1));
                   } catch (Throwable t) {
                       t.printStackTrace();
                   }                
               }
       	});
       	
       	
    //    processlistchoice(browseTab.currencyList,"Currency");
       	
      
   	
       
       	
       
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
            	
            
            	
            	showLE.setVisible(true);
            	
            }
        }); 
       	
        final  JDialogTable showPO = new JDialogTable(potablemodel);
        getLEDataCombo1(potablemodel,"PO");
        showPO.setLocationRelativeTo(this);
       	
       
        jButton8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
            	
            
            	
            	showPO.setVisible(true);
            	
            }
        }); 
        showPO.jTable1.addMouseListener(new java.awt.event.MouseAdapter() {

			@Override
			public void mouseClicked(MouseEvent e) {
				int id  = ((Integer)	showPO.jTable1.getValueAt(showPO.jTable1.getSelectedRow(),0)).intValue();
			
				 String ss = (String)	showPO.jTable1.getValueAt(showPO.jTable1.getSelectedRow(),1);
				 jTextField9.setText(ss);
				 poID = id;
				 showPO.dispose();
			}
			
    
    	
    });   
        final  JDialogTable showAgent = new JDialogTable(agenttablemodel);
        getLEDataCombo1(agenttablemodel,"Agent");
        showAgent.setLocationRelativeTo(this);
       	
       
        jButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
            	
            
            	
            	showAgent.setVisible(true);
            	
            }
        }); 
        showAgent.jTable1.addMouseListener(new java.awt.event.MouseAdapter() {

			@Override
			public void mouseClicked(MouseEvent e) {
				int id  = ((Integer)	showAgent.jTable1.getValueAt(showAgent.jTable1.getSelectedRow(),0)).intValue();
			
				 String ss = (String)	showAgent.jTable1.getValueAt(showAgent.jTable1.getSelectedRow(),1);
				 jTextField11.setText(ss);
				 agentID = id;
				 showAgent.dispose();
			}
			
    
    	
    });   
        showLE.jTable1.addMouseListener(new java.awt.event.MouseAdapter() {

			@Override
			public void mouseClicked(MouseEvent e) {
				int id  = ((Integer)	showLE.jTable1.getValueAt(showLE.jTable1.getSelectedRow(),0)).intValue();
			
				 String ss = (String)	showLE.jTable1.getValueAt(showLE.jTable1.getSelectedRow(),1);
				 jTextField3.setText(ss);
				 leID = id;
				 showLE.dispose();
			}
			
    
    	
    });   
        
        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel14)
                    .addComponent(jLabel12))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jTextField11, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jButton7, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jTextField13, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel13)
                        .addGap(18, 18, 18)
                        .addComponent(jTextField12, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel15)
                        .addGap(18, 18, 18)
                        .addComponent(jTextField14, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(384, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel12)
                    .addComponent(jTextField11, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton7)
                    .addComponent(jLabel13)
                    .addComponent(jTextField12, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel14)
                    .addComponent(jTextField13, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel15)
                    .addComponent(jTextField14, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(52, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Agent Info", jPanel1);

        deleteButton.setText("DELETE");
        deleteButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });

        saveButton.setText("SAVE");
        saveButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
            	int id =0;
            	String ss = jTextField1.getText().trim();
            	if(commonUTIL.isNumeric(ss)) {
            		id = new Integer(ss).intValue();
            		  save(id);
            	}
               
            }
        });

        saveAsNewButton.setText("SAVE AS NEW");
        saveAsNewButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
            	
            	 save(0);
            }
        });

        newButton.setText("NEW");
        newButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jButton8.setText("...");
        jButton8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton8ActionPerformed(evt);
            }
        });
        String attributeColumnName [] =    {"Attribute Name ", "Attribute  Value "};
        
        attributeModel = new DefaultTableModel(attributeColumnName,0);
        processTableData(attributeModel);
       jTable1.setModel(attributeModel);
        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addGroup(jPanel2Layout.createSequentialGroup()
                                    .addComponent(jLabel1)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(jPanel2Layout.createSequentialGroup()
                                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jTextField3, javax.swing.GroupLayout.PREFERRED_SIZE, 167, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jTextField4, javax.swing.GroupLayout.PREFERRED_SIZE, 167, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jTextField6, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jTextField5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(6, 6, 6)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(partyButton, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel2Layout.createSequentialGroup()
                                .addGap(1, 1, 1)
                                .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(10, 10, 10)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 8, Short.MAX_VALUE)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jComboBox1, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jTextField7)
                            .addComponent(jTextField8)
                            .addComponent(jTextField9, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addComponent(jButton8, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 178, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(22, 22, 22))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jTabbedPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 793, Short.MAX_VALUE)
                        .addGap(10, 10, 10))))
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(109, 109, 109)
                .addComponent(newButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(saveAsNewButton)
                .addGap(1, 1, 1)
                .addComponent(saveButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(deleteButton)
                .addContainerGap(399, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(11, 11, 11)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel1)
                            .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(jTextField3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButton1))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4)
                            .addComponent(jTextField4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel5)
                            .addComponent(jTextField5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel6)
                            .addComponent(jTextField6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jTextField7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel7))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jTextField8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel8))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jButton8)
                                    .addComponent(jTextField9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel9))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel10)
                                    .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(partyButton)))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(jLabel11)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)))
                .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(saveAsNewButton)
                    .addComponent(saveButton)
                    .addComponent(deleteButton)
                    .addComponent(newButton))
                .addGap(85, 85, 85))
        );

        jTabbedPane2.addTab("SDIMain", jPanel2);
        browseTab = new SDITab1( remoteBORef ,roles);
        browseTab.setSdi1w(this);
       // browseTab.setInitC( currencyList, remoteBORef,productTypeCombox );
        jTabbedPane2.addTab("Browse", browseTab);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jTabbedPane2)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jTabbedPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 420, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
    }// </editor-fold>

private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {
// TODO add your handling code here:
	newEvent();
}

private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {
// TODO add your handling code here:
}

private void jTextField2ActionPerformed(java.awt.event.ActionEvent evt) {
// TODO add your handling code here:
}

private void partyButtonActionPerformed(java.awt.event.ActionEvent evt) {
// TODO add your handling code here:
}

private void jTextField4ActionPerformed(java.awt.event.ActionEvent evt) {
// TODO add your handling code here:
}

private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {
// TODO add your handling code here:
}

private void jTextField3ActionPerformed(java.awt.event.ActionEvent evt) {
// TODO add your handling code here:
}

private void jButton8ActionPerformed(java.awt.event.ActionEvent evt) {
// TODO add your handling code here:
}

private void jTextField9ActionPerformed(java.awt.event.ActionEvent evt) {
// TODO add your handling code here:
}

private void jButton7ActionPerformed(java.awt.event.ActionEvent evt) {
// TODO add your handling code here:
}

private void jTextField11ActionPerformed(java.awt.event.ActionEvent evt) {
// TODO add your handling code here:
}

private void processTableData(DefaultTableModel model) {
	// TODO Auto-generated method stub
	Vector vector;
	try {
	   
		vector = (Vector) remoteBORef.getStartUPData("SDIAttributes");
		Iterator it = vector.iterator();
    	int i =0;
    	while(it.hasNext()) {
    		
    		StartUPData sdiAttributes = (StartUPData) it.next();
    	   
    		   model.insertRow(i, new Object[]{sdiAttributes.getName(),"0"});
    	    
    		i++;
    		}
    		
	} catch (RemoteException e) {
		// TODO Auto-generated catch block
		e.printStackTrace();
	}
}

private final void getMasterDataOnComboBox( javax.swing.DefaultComboBoxModel combodata,String name) {
	Vector vector = null;
	try {
		vector = (Vector) remoteBORef.getStartUPData(name);
		
		if(vector.size() > 0) {
		Iterator it = vector.iterator();
    	int i =0;
    	//combodata.insertElementAt(" ", 0);
    	
    	while(it.hasNext()) {
    		
    		StartUPData data = (StartUPData) it.next();
    	
		
			
		combodata.insertElementAt(data.getName(), i);
		i++;
	}	
    	
		}
	}catch (RemoteException e) {
				// TODO Auto-generated catch block
			
	commonUTIL.displayError("SDIWIndow","getMasterDataOnComboBox", e);
	}
}

public void processlistchoice(DefaultListModel list,String name ) {
	Vector vector;
	try {
		vector = (Vector) remoteBORef.getStartUPData(name);
		
		if(vector.size() > 0) {
		Iterator it = vector.iterator();
    	int i =0;
    	while(it.hasNext()) {
    		
    		StartUPData data = (StartUPData) it.next();
    	
		
			
    		list.addElement(data.getName());

		i++;
	}	
		}
	}catch (RemoteException e) {
				// TODO Auto-generated catch block
				e.printStackTrace();
			
}catch(Exception e) {
	commonUTIL.displayError("SDIWINDOW","getMasterDataOnComboBox", e);
}
	
}
public void getLEDataCombo1(DefaultTableModel model,String leRole) {
	Vector vector;
	try {
		
			vector = (Vector) remoteBORef.selectLEonWhereClause(" role like '%"+leRole + "%'");
		   Iterator it = vector.iterator();
    	   int i =0;
    	while(it.hasNext()) {
    		
    		LegalEntity le =	(LegalEntity) it.next();
    		model.insertRow(i, new Object[]{le.getId(),le.getName()});
    		i++;
	}	
	}catch (RemoteException e) {
				// TODO Auto-generated catch block
		commonUTIL.displayError("JFrameReportApplicatoin","getLEDataCombo1", e);
			}
	
	
}
		

public void populateMethod(javax.swing.DefaultComboBoxModel combodata) {
	Vector vector;
	try {
		vector = (Vector) remoteBORef.getStartUPData("SDIMethod");
		if(vector.size() > 0) {
			Iterator it = vector.iterator();
			int i =0;
			while(it.hasNext()) {
    	    		StartUPData data = (StartUPData) it.next();
    	    		combodata.insertElementAt(data.getName(),i);

    	    		i++;
			}	
		
		}
			
		}catch(Exception e) {
	       commonUTIL.displayError("SDIWINDOW","getMasterDataOnComboBox", e);
		}
}


private void setAttribute(String attributesV) {
	String attributeColumnName [] =    {"Attribute Name ", "Attribute  Value "};
    
    DefaultTableModel attributeModel = new DefaultTableModel(attributeColumnName,0);
    
    
		if(attributesV != null && attributesV.length() > 0) {
		String atttoken [] = attributesV.trim().split(";"); 
		
		
		for(int i =0;i<atttoken.length;i++) {
			String att = (String) atttoken[i];
			
			if(att.contains("=")) {
			String attvalue = att.substring(att.indexOf('=')+1, att.length());
			String attnameName = att.substring(0, att.indexOf('='));
			attributeModel.insertRow(i, new Object[]{attnameName.trim(),attvalue.trim()});
			}
		}
		jTable1.removeAll();
		jTable1.setModel(attributeModel);
		}
	
    
	
}


private String getAttributeValue() {
	// TODO Auto-generated method stub
	String attributesV  = "";
	for(int i=0;i<  jTable1.getRowCount();i++ ) {
		String attributename = ((String)  jTable1.getValueAt(i, 0)).trim();
		String attributeValue = ((String)  jTable1.getValueAt(i, 1)).trim();
		//attributeValue.trim();
		if(attributeValue != null && attributeValue.length() > 0)
			attributesV = attributesV.trim() + attributename+ "=" + attributeValue + ";";
		
	}
	if(attributesV.trim().length() > 0)
	return attributesV.substring(0, attributesV.length()-1);
	return attributesV;
}
    public void openSDI(Sdi sdi) {
    	   jTextField1.setText(new Integer(sdi.getId()).toString());
    	   jTextField4.setText(sdi.getCurrency());
    	   jTextField6.setSelectedItem((String) sdi.getMessageType());
    	   jTextField13.setSelectedItem((String) sdi.getAgentContacts());
    	   jTextField8.setSelectedItem((String) sdi.getLeContacts());
    	   jComboBox1.setSelectedItem((String) sdi.getProducts());
    	   jTextField7.setSelectedItem((String) sdi.getCash());
    	   
    	   
    	   agentID = sdi.getAgentId();
    	   jTextField11.setText(getLEName(sdi.getAgentId()));
    	   
    	   jTextField9.setText(getLEName(sdi.getPoId()));
    	   jTextField12.setText(sdi.getsdiformat());
    	   jTabbedPane2.setSelectedIndex(0);
    	   jTextField2.setSelectedItem(sdi.getRole());
    	   String name = getLEName(sdi.getCpId());
    	   jTextField3.setText(name);
    	   leID = sdi.getCpId();
     	  
    	   poID = sdi.getPoId();
    	   if(poID ==0) {
    		   jTextField9.setEnabled(false);
			   jButton8.setEnabled(false);
			   poID = -1; 
    	   } else {
    		   jTextField9.setEnabled(true);
			   jButton8.setEnabled(true);
    	   }
    }

  public void newEvent() {
	  jTextField1.setText("0");
	  jComboBox1.setSelectedIndex(0);
	  jTextField4.setText("ANY            ");
	  jTextField6.setSelectedIndex(0);
	  jTextField13.setSelectedIndex(0);
	  jTextField8.setSelectedIndex(0);
	  jTextField12.setText("");
	  jTextField9.setText("              ");
	  jTextField3.setText("            ");
	  jTextField11.setText("             ");
	  
	  agentID =0;
	  poID =0;
	  leID =0;
	  jTextField7.setSelectedIndex(0);
	  jTextField2.setSelectedIndex(0);
	  jTable1.removeAll();
	  for(int i=0;i < attributeModel.getRowCount();i++)
		  attributeModel.removeRow(i);
	  processTableData(attributeModel);
	//  set
	  
	  
  }


   public void save(int id) {
	   Sdi sdi = new Sdi();
	  if((jComboBox1.getSelectedItem() == null) ) {
		  showAlert("Select Product");
		  return;
	  }
		  
	  if(! showAlert(jComboBox1.getSelectedItem().toString(),"Select Product")) 
		  return;
	    
	   if(! showAlert(jTextField4.getText().trim(),"Select  Currency")) 
			  return;
	   if((jTextField6.getSelectedItem() == null) ) {
			  showAlert("Select Method");
			  return;
		  }
	   if((jTextField13.getSelectedItem() == null) ) {
			  showAlert("Select Agent Contact");
			  return;
		  }
	   if((jTextField8.getSelectedItem() == null) ) {
			  showAlert("Select LE Contact");
			  return;
		  }
	   
	   if(! showAlert(jTextField6.getSelectedItem().toString(),"Select  METHOD")) 
			  return;
	   
	  
	   if(! showAlert(jTextField13.getSelectedItem().toString(),"Select Agent Contact  ")) 
			  return;
	   if(! showAlert(jTextField8.getSelectedItem().toString()," Select LE Contact  ")) 
			  return;
	   if(! showAlert(jTextField12.getText().trim()," Select Account   ")) 
			  return;
	   if(agentID == 0)  {
		   commonUTIL.showAlertMessage("Select Agent " );
	       return;
	   }
	   if(poID == 0 && (!jTextField2.getSelectedItem().toString().equalsIgnoreCase("PO")))   {
		   commonUTIL.showAlertMessage("Select PO " );
		   return;
	   }
	   if(leID == 0)  {
		   commonUTIL.showAlertMessage("Select CounterParty " );
		   return;
	   }
	   
	   sdi.setAgentId(agentID);
	   if( poID == -1) 
		   poID =0;
	   sdi.setPoId(poID);
	   sdi.setCpId(leID);
	   sdi.setCash(jTextField7.getSelectedItem().toString().trim());
	   sdi.setPayrec(jTextField5.getSelectedItem().toString().trim());
	   sdi.setProducts(jComboBox1.getSelectedItem().toString().trim());
	   sdi.setAccountID(0);
	   sdi.setCurrency(jTextField4.getText().trim());
	   sdi.setMessageType(jTextField6.getSelectedItem().toString().trim());
	   sdi.setLeContacts(jTextField8.getSelectedItem().toString().trim());
	   sdi.setAgentContacts(jTextField13.getSelectedItem().toString().trim());
	   sdi.setAttributes(getAttributeValue());
	   sdi.setsdiformat(jTextField12.getText().trim());
	   sdi.setRole(jTextField2.getSelectedItem().toString());
	   
	   String key = sdi.getAgentId()+"/"+sdi.getsdiformat() +"/"+sdi.getProducts()+"/"+sdi.getCpId()+"/"+sdi.getPoId()+"/"+sdi.getCurrency();
	   sdi.setkey(key);
	   sdi.setId(id);
	   try {
	
	if(id == 0) {
		if(!remoteBORef.checkSDIKey(sdi)) {
			sdi =	(Sdi) remoteBORef.saveSDI(sdi);	
		
			jTextField1.setText(new Integer(sdi.getId()).toString());
			commonUTIL.showAlertMessage("SDi save with id " + sdi.getId() );
		} 
	} else {
		sdi =	(Sdi) remoteBORef.saveSDI(sdi);
		poID = sdi.getPoId();
		
	    commonUTIL.showAlertMessage("SDi updated with id " + sdi.getId() );
	}
	} catch (RemoteException e) {
		// TODO Auto-generated catch block
	   commonUTIL.displayError("SDIWindow", "Save " , e);
	}
   }

   public boolean showAlert(String value,String message) {
	   if(commonUTIL.isEmpty(value)) {
		   commonUTIL.showAlertMessage(message );
		   return false;
   }
   return true;
   }
   
   public String getLEName(int id) {
	   String name = "";
	   try {
		   if(id ==0)
			   return name;
		LegalEntity le = (LegalEntity )remoteBORef.selectLE(id);
		name = le.getName();
	} catch (RemoteException e) {
		// TODO Auto-generated catch block
		e.printStackTrace();
	}
	   return name;
   }

   public void showAlert(String message) {
	
		   commonUTIL.showAlertMessage(message );
		 
  
   }
 
   
    // Variables declaration - do not modify
    private javax.swing.JButton jButton1;
    private javax.swing.JButton partyButton;
    private javax.swing.JButton newButton;
    private javax.swing.JButton saveAsNewButton;
    private javax.swing.JButton saveButton;
    private javax.swing.JButton deleteButton;
    private javax.swing.JButton jButton7;
    private javax.swing.JButton jButton8;
    private javax.swing.JComboBox jComboBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTabbedPane jTabbedPane2;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField11;
    private javax.swing.JTextField jTextField12;
    private javax.swing.JComboBox jTextField13;
    private javax.swing.JTextField jTextField14;
    private javax.swing.JComboBox jTextField2;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JTextField jTextField4;
    private javax.swing.JComboBox jTextField5;
    private javax.swing.JComboBox jTextField6;
    private javax.swing.JComboBox jTextField7;
    private javax.swing.JComboBox jTextField8;
    private javax.swing.JTextField jTextField9;
    // End of variables declaration
}
