package apps.window.tradewindow.FXPanels;

import java.awt.event.MouseEvent;
import java.awt.event.MouseListener;
import java.rmi.RemoteException;
import java.util.Iterator;
import java.util.Vector;

import javax.jms.Connection;
import javax.jms.Destination;
import javax.jms.ExceptionListener;
import javax.jms.JMSException;
import javax.jms.Message;
import javax.jms.MessageConsumer;
import javax.jms.ObjectMessage;
import javax.jms.Session;
import javax.swing.JButton;
import javax.swing.JTable;
import javax.swing.SwingUtilities;
import javax.swing.table.AbstractTableModel;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableColumnModel;

import org.apache.activemq.ActiveMQConnectionFactory;

import util.commonUTIL;
import beans.Openpos;
import beans.Position;
import beans.Trade;
import dsServices.RemoteMO;
import dsServices.RemoteTrade;
import dsServices.ServerConnectionUtil;

/**
 *
 * @author MPankaj
 */
public class Funtionality extends javax.swing.JPanel  implements Runnable , ExceptionListener  {

    /** Creates new form Funtionality */
	RemoteMO remotemo = null;
	 static private String hostName = "";
	 ServerConnectionUtil de = null;
	 DefaultTableModel positionModel = null;
	 String positiongcol [] = {"DATE     ","primaryC","quotingC"};
	 String routingCol [] =  {"Book", "CP", "PrimaryCurr", "QuotingCurr"};
	 DefaultTableModel  routingModel = null;
	  public Funtionality() {
	        initComponents();
	        hostName = commonUTIL.getLocalHostName();
	    }

	    /** This method is called from within the constructor to
	     * initialize the form.
	     * WARNING: Do NOT modify this code. The content of this method is
	     * always regenerated by the Form Editor.
	     */
	    
	 
	    @SuppressWarnings("unchecked")
	    // <editor-fold defaultstate="collapsed" desc="Generated Code">
	    public void initComponents() {
	    	de =ServerConnectionUtil.connect("localhost", 1099,commonUTIL.getServerIP());
		   	 try {
		   		remotemo = (RemoteMO) de.getRMIService("MO");
		   	 } catch (RemoteException e) {
					// TODO Auto-generated catch block
					e.printStackTrace();
				}
	        jPanel1 = new javax.swing.JPanel();
	        jPanel4 = new javax.swing.JPanel();
	        jButton6 = new javax.swing.JButton();
	        jButton5 = new javax.swing.JButton();
	        jButton4 = new javax.swing.JButton();
	        jButton1 = new javax.swing.JButton();
	        jButton2 = new javax.swing.JButton();
	        jButton3 = new javax.swing.JButton();
	        jPanel2 = new javax.swing.JPanel();
	        jPanel5 = new javax.swing.JPanel();
	        jPanel3 = new javax.swing.JPanel();
	        jScrollPane1 = new javax.swing.JScrollPane();
	        jTable1 = new javax.swing.JTable();
	        jScrollPane2 = new javax.swing.JScrollPane();
	        jTable2 = new javax.swing.JTable();
	        jTabbedPane1 = new javax.swing.JTabbedPane();
	        jScrollPane4 = new javax.swing.JScrollPane();
	        jTable4 = new javax.swing.JTable();
	        jScrollPane5 = new javax.swing.JScrollPane();
	        jTable5 = new javax.swing.JTable();
	        jScrollPane6 = new javax.swing.JScrollPane();
	        jTable6 = new javax.swing.JTable();
	        jScrollPane3 = new javax.swing.JScrollPane();
	        jTable3 = new javax.swing.JTable();
	        jTabbedPane2 = new javax.swing.JTabbedPane();

	     //   setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

	        jButton6.setText("SAVE");

	        jButton5.setText("DEAL");

	        jButton4.setText("NEW");

	        jTabbedPane1.setVisible(false);
	        jButton1.setText("FAV");

	        jButton2.setText("INTERNAL");

	        jButton3.setText("B2B");
	        
	        jButton1.addMouseListener(new java.awt.event.MouseAdapter() {

				@Override
				public void mouseClicked(MouseEvent e) {
					
					jTabbedPane1.setVisible(true);
					   jPanel3.setVisible(false);
				   
				   
					
				}

				
	        
	        	
	        });

	        jButton2.addMouseListener(new java.awt.event.MouseAdapter() {

				@Override
				public void mouseClicked(MouseEvent e) {
					
					jTabbedPane1.setVisible(false);
					   jPanel3.setVisible(true);
				   
				   
					
				}

				
	        
	        	
	        });
	        

	       
	        positionModel = new DefaultTableModel (positiongcol,0);
	        jTable1.setModel(positionModel);
	        jScrollPane1.setViewportView(jTable1);
	        routingModel = new DefaultTableModel (routingCol,0);
	        jTable2.setModel(routingModel);
	        jScrollPane2.setViewportView(jTable2);
	        jTabbedPane2.addTab("Routing", jScrollPane2);
	        jTabbedPane2.addTab("Position", jScrollPane1);
	        
	        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
	        jPanel5.setLayout(jPanel5Layout);
	        jPanel5Layout.setHorizontalGroup(
	            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
	            .addGroup(jPanel5Layout.createSequentialGroup()
	                .addContainerGap()
	                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 400, Short.MAX_VALUE)
	                .addContainerGap())
	        );
	        jPanel5Layout.setVerticalGroup(
	            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
	            .addGroup(jPanel5Layout.createSequentialGroup()
	                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)
	                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
	        );

	        jTabbedPane2.addTab("Position", jPanel5);

	        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
	        jPanel3.setLayout(jPanel3Layout);
	        jPanel3Layout.setHorizontalGroup(
	            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
	            .addGroup(jPanel3Layout.createSequentialGroup()
	                .addContainerGap()
	                .addComponent(jTabbedPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 382, Short.MAX_VALUE)
	                .addContainerGap())
	        );
	        jPanel3Layout.setVerticalGroup(
	            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
	            .addGroup(jPanel3Layout.createSequentialGroup()
	                .addContainerGap()
	                .addComponent(jTabbedPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 111, Short.MAX_VALUE)
	                .addContainerGap())
	        );

	        jTable4.setModel(new javax.swing.table.DefaultTableModel(
	            new Object [][] {
	                {null, null, null, null},
	                {null, null, null, null},
	                {null, null, null, null},
	                {null, null, null, null}
	            },
	            new String [] {
	                "Title 1", "Title 2", "Title 3", "Title 4"
	            }
	        ));
	        jScrollPane4.setViewportView(jTable4);

	        jTabbedPane1.addTab("tab2", jScrollPane4);

	        jTable5.setModel(new javax.swing.table.DefaultTableModel(
	            new Object [][] {
	                {null, null, null, null},
	                {null, null, null, null},
	                {null, null, null, null},
	                {null, null, null, null}
	            },
	            new String [] {
	                "Title 1", "Title 2", "Title 3", "Title 4"
	            }
	        ));
	        jScrollPane5.setViewportView(jTable5);

	        jTabbedPane1.addTab("tab3", jScrollPane5);

	        jTable6.setModel(new javax.swing.table.DefaultTableModel(
	            new Object [][] {
	                {null, null, null, null},
	                {null, null, null, null},
	                {null, null, null, null},
	                {null, null, null, null}
	            },
	            new String [] {
	                "Title 1", "Title 2", "Title 3", "Title 4"
	            }
	        ));
	        jScrollPane6.setViewportView(jTable6);

	        jTabbedPane1.addTab("tab4", jScrollPane6);

	        jTable3.setModel(new javax.swing.table.DefaultTableModel(
	            new Object [][] {
	                {null, null, null, null},
	                {null, null, null, null},
	                {null, null, null, null},
	                {null, null, null, null}
	            },
	            new String [] {
	                "Title 1", "Title 2", "Title 3", "Title 4"
	            }
	        ));
	        jScrollPane3.setViewportView(jTable3);

	        jTabbedPane1.addTab("tab1", jScrollPane3);

	        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
	        jPanel2.setLayout(jPanel2Layout);
	        jPanel2Layout.setHorizontalGroup(
	            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
	            .addGroup(jPanel2Layout.createSequentialGroup()
	                .addContainerGap()
	                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
	                .addContainerGap(30, Short.MAX_VALUE))
	            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
	                .addGroup(jPanel2Layout.createSequentialGroup()
	                    .addContainerGap()
	                    .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 425, javax.swing.GroupLayout.PREFERRED_SIZE)
	                    .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
	        );
	        jPanel2Layout.setVerticalGroup(
	            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
	            .addGroup(jPanel2Layout.createSequentialGroup()
	                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
	                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
	            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
	                .addGroup(jPanel2Layout.createSequentialGroup()
	                    .addContainerGap()
	                    .addComponent(jTabbedPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 122, Short.MAX_VALUE)
	                    .addContainerGap()))
	        );

	        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
	        jPanel4.setLayout(jPanel4Layout);
	        jPanel4Layout.setHorizontalGroup(
	            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
	            .addGroup(jPanel4Layout.createSequentialGroup()
	                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
	                    .addComponent(jPanel2, javax.swing.GroupLayout.Alignment.LEADING, 0, 442, Short.MAX_VALUE)
	                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel4Layout.createSequentialGroup()
	                        .addContainerGap()
	                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
	                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
	                        .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
	                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
	                        .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
	                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
	                        .addComponent(jButton4, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
	                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
	                        .addComponent(jButton5, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
	                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
	                        .addComponent(jButton6, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)))
	                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
	        );

	        jPanel4Layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {jButton1, jButton2, jButton3, jButton4, jButton5, jButton6});

	        jPanel4Layout.setVerticalGroup(
	            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
	            .addGroup(jPanel4Layout.createSequentialGroup()
	                .addContainerGap()
	                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
	                    .addComponent(jButton1)
	                    .addComponent(jButton3)
	                    .addComponent(jButton2)
	                    .addComponent(jButton4)
	                    .addComponent(jButton5)
	                    .addComponent(jButton6))
	                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
	                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE)
	                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
	        );

	        jPanel4Layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {jButton1, jButton2, jButton3, jButton4, jButton5, jButton6});

	        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
	        jPanel1.setLayout(jPanel1Layout);
	        jPanel1Layout.setHorizontalGroup(
	            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
	            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
	                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
	                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
	                .addGap(35, 35, 35))
	        );
	        jPanel1Layout.setVerticalGroup(
	            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
	            .addGroup(jPanel1Layout.createSequentialGroup()
	                .addContainerGap()
	                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
	                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
	        );

	        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
	      //  getContentPane().setLayout(layout);
	        layout.setHorizontalGroup(
	            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
	            .addGroup(layout.createSequentialGroup()
	                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 474, javax.swing.GroupLayout.PREFERRED_SIZE)
	                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
	        );
	        layout.setVerticalGroup(
	            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
	            .addGroup(layout.createSequentialGroup()
	                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 197, javax.swing.GroupLayout.PREFERRED_SIZE)
	                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
	        );

	     //   pack();
	    }// </editor-fold>

	    /**
	     * @param args the command line arguments
	     */
	    public static void main(String args[]) {
	        /* Set the Nimbus look and feel */
	        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
	        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
	         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
	         */
	        try {
	            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
	                if ("Nimbus".equals(info.getName())) {
	                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
	                    break;
	                }
	            }
	        } catch (ClassNotFoundException ex) {
	            java.util.logging.Logger.getLogger(Funtionality.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
	        } catch (InstantiationException ex) {
	            java.util.logging.Logger.getLogger(Funtionality.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
	        } catch (IllegalAccessException ex) {
	            java.util.logging.Logger.getLogger(Funtionality.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
	        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
	            java.util.logging.Logger.getLogger(Funtionality.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
	        }
	        //</editor-fold>

	        /* Create and display the form */
	        java.awt.EventQueue.invokeLater(new Runnable() {

	            public void run() {
	                new Funtionality().setVisible(true);
	            }
	        });
	    }
	    
	    
	    public void refreshPositionTable(String currencyPair,int bookID) {
	    	primaryCurr = currencyPair.substring(0,3);
	    	quotingCurr = currencyPair.substring(4,currencyPair.length());
	    	positiongcol[0] = "DATE     ";
	    	positiongcol[1] =  quotingCurr;
	    	positiongcol[2] =primaryCurr;
	    	bookid = bookID;
	    	positionModel = new DefaultTableModel(positiongcol,0);
	    	refreshPositionTable();
	    	
	    }
	    public void refreshPositionTable() {
	    	try{
	    		Vector openpos = (Vector) remotemo.getOpenPositionOnProductSubType(primaryCurr+"/"+quotingCurr);
	    		 Iterator it = openpos.iterator();
	    		 while(it.hasNext()) {
	    			 Openpos openp = (Openpos) it.next();
	    		     String date = openp.getProductSubType().substring(openp.getProductSubType().indexOf('_'), openp.getProductSubType().indexOf('_') +10);
	    			 positionModel.insertRow(positionModel.getRowCount(), new Object[]{date,openp.getQuotingAmt(),openp.getOpenNominal()});
	    		 }
	    		 
	    		 jTable1.removeAll();
	    		 jTable1.setModel(positionModel);
	    		 
	    	} catch(RemoteException e) {
	    } 
	    }
	    
	    public void refreshTables(String currencyPair,String bookName,int bookID) {
	    	jTabbedPane1.setVisible(false);
			jPanel3.setVisible(true);
			jPanel5.setBorder(javax.swing.BorderFactory.createTitledBorder(bookName));
			refreshPositionTable(currencyPair,bookID);
	    }
	    @Override
		public synchronized void run() {
			for( ; ; ) {
				try {
					
					  ActiveMQConnectionFactory connectionFactory = new ActiveMQConnectionFactory("tcp://"+hostName+":61616");

			            // Create a Connection
			            Connection connection = connectionFactory.createConnection();
			            connection.start();

			            connection.setExceptionListener(this);

			            // Create a Session
			            Session session = connection.createSession(false, Session.AUTO_ACKNOWLEDGE);

			            // Create the destination (Topic or Queue)
			            Destination destination = session.createQueue("POSITION");

			            // Create a MessageConsumer from the Session to the Topic or Queue
			            MessageConsumer consumer = session.createConsumer(destination);
			            Message message = consumer.receive(12000);

			            if (message instanceof ObjectMessage) {
			            	ObjectMessage oMessage = (ObjectMessage) message;

			            	Position pos = (Position) oMessage.getObject();
			                System.out.println("From Funcationality start Process Position for Pos "+ pos.getPositionId());
			               
			              
			                System.out.println("FromFuncationality  End Processing Position for Pos "+ pos.getPositionId());
			                refreshPositionTable();
			    			//Thread.sleep(8000);
			            } 

			            consumer.close();
			            session.close();
			            connection.close();
			        
					
				} catch (JMSException j) {
					// TODO Auto-generated catch block
					j.printStackTrace();
				} catch(Exception e) {
					 commonUTIL.displayError("PositionManager", "run()", e);
				 }
			}
			
		}
		@Override
		public void onException(JMSException e) {
			commonUTIL.displayError("PositionManager","Error in listening" , e);
			
		}
	    // Variables declaration - do not modify
	    public String primaryCurr = "";
	    public String quotingCurr = "";
	    int bookid = 0;
	    public javax.swing.JButton jButton1;
	    public javax.swing.JButton jButton2;
	    public javax.swing.JButton jButton3;
	    public javax.swing.JButton jButton4;
	    public javax.swing.JButton jButton5;
	    public javax.swing.JButton jButton6;
	    public javax.swing.JPanel jPanel1;
	    public javax.swing.JPanel jPanel2;
	    public javax.swing.JPanel jPanel3;
	    public javax.swing.JPanel jPanel4;
	    public javax.swing.JPanel jPanel5;
	    public javax.swing.JScrollPane jScrollPane1;
	    public javax.swing.JScrollPane jScrollPane2;
	    public javax.swing.JScrollPane jScrollPane3;
	    public javax.swing.JScrollPane jScrollPane4;
	    public javax.swing.JScrollPane jScrollPane5;
	    public javax.swing.JScrollPane jScrollPane6;
	    public javax.swing.JTabbedPane jTabbedPane1;
	    public javax.swing.JTable jTable1;
	    public javax.swing.JTable jTable2;
	    public javax.swing.JTable jTable3;
	    public javax.swing.JTable jTable4;
	    public javax.swing.JTable jTable5;
	    public javax.swing.JTable jTable6;
	    public javax.swing.JTabbedPane jTabbedPane2;
	    // End of variables declaration
	}
