package apps.window.staticwindow;

import java.awt.event.MouseEvent;
import java.rmi.RemoteException;
import java.util.Enumeration;
import java.util.Hashtable;
import java.util.Iterator;
import java.util.Vector;

import javax.swing.DefaultCellEditor;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JComboBox;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

import beans.CurrencyDefault;
import beans.CurrencyPair;
import beans.Holiday;

import util.commonUTIL;
import dsServices.RemoteReferenceData;
import dsServices.ServerConnectionUtil;

/* * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * CurrencyDefault.java
 *
 * Created on 10 Jul, 2013, 1:43:07 PM
 */
/**
 *
 * @author MPankaj
 */
public class CurrencyDefaultWindow extends javax.swing.JPanel {
	public static  ServerConnectionUtil de = null;
	RemoteReferenceData remoteBORef;
	DefaultTableModel tmodel = null;
	DefaultTableModel cpmodel = null;
	 javax.swing.DefaultComboBoxModel country = new javax.swing.DefaultComboBoxModel();
	 javax.swing.DefaultComboBoxModel primcurrency = new javax.swing.DefaultComboBoxModel();
	
	 Hashtable currencyDefaultData = new Hashtable();
    /** Creates new form CurrencyDefault */
	 public CurrencyDefaultWindow() {
	        initComponents();
	    }

	    /** This method is called from within the constructor to
	     * initialize the form.
	     * WARNING: Do NOT modify this code. The content of this method is
	     * always regenerated by the Form Editor.
	     */
	    @SuppressWarnings("unchecked")
	    // <editor-fold defaultstate="collapsed" desc="Generated Code">
	    private void initComponents() {
	    	de =ServerConnectionUtil.connect("localhost", 1099,commonUTIL.getServerIP());
	     	 try {
	     		
	     		 remoteBORef = (RemoteReferenceData) de.getRMIService("ReferenceData");
	     	//	Vector allCurrencyDefaults =  (Vector) remoteBORef.selectALLCurrencyDefault();
	  			
	  		//System.out.println(remoteBORef);
	  	
	     	 } catch (RemoteException e) {
	  			// TODO Auto-generated catch block
	  			commonUTIL.displayError(this.getName(), "initComponents", e);
	  	}
	        jPanel1 = new javax.swing.JPanel();
	        jScrollPane1 = new javax.swing.JScrollPane();
	        jTable1 = new javax.swing.JTable();
	        jTabbedPane1 = new javax.swing.JTabbedPane();
	        jPanel2 = new javax.swing.JPanel();
	        jLabel1 = new javax.swing.JLabel();
	        jTextField1 = new javax.swing.JTextField();
	        jButton1 = new javax.swing.JButton();
	        jLabel2 = new javax.swing.JLabel();
	        jTextField2 = new javax.swing.JTextField();
	        jLabel3 = new javax.swing.JLabel();
	        jComboBox1 = new javax.swing.JComboBox();
	        jLabel4 = new javax.swing.JLabel();
	        jTextField3 = new javax.swing.JTextField();
	        jLabel5 = new javax.swing.JLabel();
	        jComboBox2 = new javax.swing.JComboBox();
	        jLabel6 = new javax.swing.JLabel();
	        jTextField4 = new javax.swing.JTextField();
	        jLabel7 = new javax.swing.JLabel();
	        jTextField5 = new javax.swing.JTextField();
	        jLabel8 = new javax.swing.JLabel();
	        jTextField6 = new javax.swing.JTextField();
	        jCheckBox1 = new javax.swing.JCheckBox();
	        jCheckBox2 = new javax.swing.JCheckBox();
	        jButton2 = new javax.swing.JButton();
	        jButton3 = new javax.swing.JButton();
	        jPanel3 = new javax.swing.JPanel();
	        jButton4 = new javax.swing.JButton();
	        jButton5 = new javax.swing.JButton();
	        jScrollPane2 = new javax.swing.JScrollPane();
	        jTable2 = new javax.swing.JTable();
	        jLabel9 = new javax.swing.JLabel();
	        jComboBox3 = new javax.swing.JComboBox();
	        jCheckBox3 = new javax.swing.JCheckBox();
	        jLabel10 = new javax.swing.JLabel();
	        jTextField7 = new javax.swing.JTextField();
	        jLabel11 = new javax.swing.JLabel();
	        jLabel12 = new javax.swing.JLabel();
	        jTextField8 = new javax.swing.JTextField();
	        jTextField9 = new javax.swing.JTextField();
	        jLabel13 = new javax.swing.JLabel();
	        jTextField10 = new javax.swing.JTextField();
	        jButton6 = new javax.swing.JButton();
	        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(""));
	       jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(""));
	       jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder(""));
	     //   setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

	        String col[] = {"Currency"};
	        tmodel = new DefaultTableModel(col,0);
	        jTable1.setModel(tmodel);
	        jScrollPane1.setViewportView(jTable1);

	        jLabel1.setText("CURRENCY");

	        jTextField1.setText("       ");

	        jButton1.setText("jButton1");

	        jLabel2.setText("ISO CODE");

	        jTextField2.setText("       ");

	        jLabel3.setText("COUNTRY");
	        getCurrencyDefaultData(tmodel,country);
	        jComboBox1.setModel(country);

	        jLabel4.setText("SPOTS DAYS");

	        jTextField3.setText(" 0  ");

	        jLabel5.setText("HOLIDAY");

	        jComboBox2.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

	        jLabel6.setText("ROUNDING");

	        jTextField4.setText("  0    ");

	        jLabel7.setText("DECMIALS");

	        jTextField5.setText("  0    ");

	        jLabel8.setText("RATE DECIALS");

	        jTextField6.setText("   0      ");
	        jTable1.addMouseListener(new java.awt.event.MouseAdapter() {

				@Override
				public void mouseClicked(MouseEvent e) {
					int rowindex = jTable1.getSelectedRow(); 
					
					jCheckBox1.setSelected(false);
					jCheckBox2.setSelected(false);
				   jComboBox1.setSelectedIndex(rowindex);
				   CurrencyDefault cd =  (CurrencyDefault)currencyDefaultData.get(rowindex);
				   jTable2.removeAll();
				  
				   String[] columnNames =  {"Prim","Sec","Pair pos Ref","Divide","Quote Factor", "Point Factor","Spot Days"};
			        cpmodel = new DefaultTableModel(columnNames, 0);
			    
                   
                
				   processTableData(cpmodel,cd.getCurrency_code());
				    jTable2.setModel(cpmodel);
				   jTextField1.setText(cd.getCurrency_code());
				   jTextField7.setText(cd.getCurrency_code());
				   jTextField2.setText(cd.getIso_code());
				   jTextField3.setText(new Integer(cd.getSpot_days()).toString());
				   jTextField4.setText(new Integer(cd.getRounding()).toString());
				   jTextField5.setText("              ");
				   jTextField6.setText("              ");
				   if(cd.getIs_precious_metal_b() == 1)
					   jCheckBox1.setSelected(true);
				   if(cd.getNon_deliverable_b() == 1)
					   jCheckBox2.setSelected(true);
				   
				   
				}
	        });
	        jCheckBox1.setLabel("Presious Metal");
	        jCheckBox1.addActionListener(new java.awt.event.ActionListener() {
	            public void actionPerformed(java.awt.event.ActionEvent evt) {
	                jCheckBox1ActionPerformed(evt);
	            }
	        });

	        jCheckBox2.setLabel("Non Deliverable ");

	        jButton2.setText("SAVE");
	        jButton2.addActionListener(new java.awt.event.ActionListener() {
	            public void actionPerformed(java.awt.event.ActionEvent evt) {
	            	int rowindex = jTable1.getSelectedRow(); 
	            	  jComboBox1.setSelectedIndex(rowindex);
	   			   CurrencyDefault cd =  (CurrencyDefault)currencyDefaultData.get(rowindex);
	   			  
	   			   cd.setCurrency_code(jTextField1.getText());
	   			cd.setCurrency_code(jTextField1.getText());
	   			cd.setIso_code(jTextField2.getText());
	   			cd.setSpot_days(new Integer(jTextField3.getText()).intValue());
	   			cd.setRounding(new Integer(jTextField4.getText()).intValue());
	   			
	   			   
	   			   if(jCheckBox1.isSelected())   				   
	   			      cd.setIs_precious_metal_b(1);
	   			   
	   			   if(jCheckBox2.isSelected())
	   				cd.setNon_deliverable_b(1);
	   			   
	   			   try {
					remoteBORef.updateCurrencyDefault(cd);
				} catch (RemoteException e) {
					// TODO Auto-generated catch block
					e.printStackTrace();
				}
	            }
	        });


	        jButton3.setText("DELETE");
	        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder("Price"));
	        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
	        jPanel2.setLayout(jPanel2Layout);
	        jPanel2Layout.setHorizontalGroup(
	            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
	            .addGroup(jPanel2Layout.createSequentialGroup()
	                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
	                    .addGroup(jPanel2Layout.createSequentialGroup()
	                        .addGap(19, 19, 19)
	                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
	                            .addComponent(jCheckBox2)
	                            .addComponent(jCheckBox1)
	                            .addGroup(jPanel2Layout.createSequentialGroup()
	                                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)
	                                .addGap(28, 28, 28)
	                                .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
	                                .addGap(18, 18, 18)
	                                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
	                                .addGap(18, 18, 18)
	                                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)
	                                .addGap(28, 28, 28)
	                                .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
	                                .addGap(18, 18, 18)
	                                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)
	                                .addGap(18, 18, 18)
	                                .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE))
	                            .addGroup(jPanel2Layout.createSequentialGroup()
	                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
	                                    .addGroup(jPanel2Layout.createSequentialGroup()
	                                        .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)
	                                        .addGap(28, 28, 28)
	                                        .addComponent(jTextField3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
	                                    .addGroup(jPanel2Layout.createSequentialGroup()
	                                        .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)
	                                        .addGap(28, 28, 28)
	                                        .addComponent(jTextField4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
	                                .addGap(30, 30, 30)
	                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
	                                    .addGroup(jPanel2Layout.createSequentialGroup()
	                                        .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)
	                                        .addGap(28, 28, 28)
	                                        .addComponent(jTextField5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
	                                        .addGap(18, 18, 18)
	                                        .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
	                                        .addGap(18, 18, 18)
	                                        .addComponent(jTextField6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
	                                    .addGroup(jPanel2Layout.createSequentialGroup()
	                                        .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)
	                                        .addGap(18, 18, 18)
	                                        .addComponent(jComboBox2, javax.swing.GroupLayout.PREFERRED_SIZE, 262, javax.swing.GroupLayout.PREFERRED_SIZE))))))
	                    .addGroup(jPanel2Layout.createSequentialGroup()
	                        .addGap(61, 61, 61)
	                        .addComponent(jButton2)
	                        .addGap(41, 41, 41)
	                        .addComponent(jButton3)))
	                .addContainerGap(25, Short.MAX_VALUE))
	        );

	        jPanel2Layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {jButton1, jLabel1, jLabel2, jTextField1, jTextField2});

	        jPanel2Layout.setVerticalGroup(
	            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
	            .addGroup(jPanel2Layout.createSequentialGroup()
	                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
	                    .addGroup(jPanel2Layout.createSequentialGroup()
	                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
	                            .addGroup(jPanel2Layout.createSequentialGroup()
	                                .addContainerGap()
	                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
	                                    .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
	                                    .addComponent(jTextField1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
	                            .addGroup(jPanel2Layout.createSequentialGroup()
	                                .addGap(11, 11, 11)
	                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
	                                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
	                                        .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
	                                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
	                                            .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
	                                            .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
	                                            .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
	                                    .addComponent(jButton1))))
	                        .addGap(18, 18, 18)
	                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
	                            .addComponent(jLabel4, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
	                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
	                                .addComponent(jTextField3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
	                                .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
	                                .addComponent(jComboBox2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
	                        .addGap(18, 18, 18)
	                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
	                            .addComponent(jLabel6, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
	                            .addComponent(jLabel7, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
	                            .addComponent(jTextField5, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
	                            .addComponent(jLabel8, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
	                            .addComponent(jTextField6, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
	                        .addGap(48, 48, 48)
	                        .addComponent(jCheckBox1)
	                        .addGap(18, 18, 18)
	                        .addComponent(jCheckBox2)
	                        .addGap(58, 58, 58))
	                    .addGroup(jPanel2Layout.createSequentialGroup()
	                        .addContainerGap(96, Short.MAX_VALUE)
	                        .addComponent(jTextField4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
	                        .addGap(170, 170, 170)))
	                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 85, Short.MAX_VALUE)
	                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
	                    .addComponent(jButton2)
	                    .addComponent(jButton3))
	                .addGap(90, 90, 90))
	        );

	        jPanel2Layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {jButton1, jLabel1, jTextField1});

	        jCheckBox1.getAccessibleContext().setAccessibleName(" Presious Metal");

	        jTabbedPane1.addTab("Currency Default", jPanel2);

	        jButton4.setText("ADD");

	        jButton5.setText("EDIT");
	        String[] columnNames =  {"Prim","Sec","Pair pos Ref","Divide","Quote Factor", "Point Factor","Spot Days"};
	        cpmodel = new DefaultTableModel(columnNames, 0);
	        jTable2.setModel(cpmodel);
	        jScrollPane2.setViewportView(jTable2);

	        jLabel9.setText("Primary Currency");

	        jComboBox3.setModel(primcurrency);

	        jCheckBox3.setText("Pair Pos Ref");
	        jCheckBox3.addActionListener(new java.awt.event.ActionListener() {
	            public void actionPerformed(java.awt.event.ActionEvent evt) {
	                jCheckBox3ActionPerformed(evt);
	            }
	        });

	        
	        
	        
	        
	        jLabel10.setText("Secondary Currency");

	        jTextField7.setText("      ");

	        jLabel11.setText("Divide ");

	        jLabel12.setText("Rounding");

	        jTextField8.setText("    ");

	        jTextField9.setText("     ");

	        jLabel13.setText("Spot Days");

	        jTextField10.setText("    ");
	        jTextField10.addActionListener(new java.awt.event.ActionListener() {
	            public void actionPerformed(java.awt.event.ActionEvent evt) {
	                jTextField10ActionPerformed(evt);
	            }
	        });
	        jButton4.addActionListener(new java.awt.event.ActionListener() {
	            public void actionPerformed(java.awt.event.ActionEvent evt) {
	            	String pcurrency = jComboBox3.getSelectedItem().toString();
	            	CurrencyPair cp = new CurrencyPair();
	            	cp.setPrimary_currency(pcurrency);
	            	cp.setQuoting_currency(jTextField7.getText());
	            	cp.setQuote_factor(new Integer(jTextField8.getText().trim()).intValue());
	            	cp.setSpot_days(new Integer(jTextField10.getText().trim()).intValue());
	   			   cp.setRounding(new Integer(jTextField9.getText().trim()).intValue());
	   			   cp.setBp_factor(0);
	   			   if(cp.getQuoting_currency() == null || cp.getQuoting_currency().length() == 0) {
	   				JOptionPane.showMessageDialog(null,"Please select Secondary Currency",null,
	   		  				JOptionPane.INFORMATION_MESSAGE);
	   				return;
	            }
	   			if(cp.getPrimary_currency().equalsIgnoreCase(cp.getQuoting_currency())) {
	   				JOptionPane.showMessageDialog(null,"Primary Currency and  Secondary Currency are same ",null,
	   		  				JOptionPane.INFORMATION_MESSAGE);
	   				return;
	            }
	   			   if(jCheckBox3.isSelected())   				   
	   			      cp.setPair_pos_ref_b(1);
	   			  
	   			   
	   			   try {
					if(remoteBORef.saveCurrencyPair(cp)) {
						//model.insertRow(i, new Object[]{cp.getCurrency_code()});
					//	if(cpmodel.getRowCount() ==0 ) {
							cpmodel.insertRow(0,new Object[]{cp.getPrimary_currency(),cp.getQuoting_currency(),cp.getPair_pos_ref_b(),cp.getBp_factor(),cp.getQuote_factor(),cp.getSpot_days() });
						//}
						//else {
						
					//	cpmodel.insertRow(cpmodel.getRowCount()+1,new Object[]{cp.getPrimary_currency(),cp.getQuoting_currency(),cp.getPair_pos_ref_b(),cp.getBp_factor(),cp.getQuote_factor(),cp.getSpot_days() });
						//}
						}
				} catch (RemoteException e) {
					// TODO Auto-generated catch block
					e.printStackTrace();
				}
	            }
	        });

	        jButton6.setText("DELETE");

	        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
	        jPanel3.setLayout(jPanel3Layout);
	        jPanel3Layout.setHorizontalGroup(
	            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
	            .addGroup(jPanel3Layout.createSequentialGroup()
	                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
	                    .addGroup(jPanel3Layout.createSequentialGroup()
	                        .addContainerGap()
	                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 638, javax.swing.GroupLayout.PREFERRED_SIZE))
	                    .addGroup(jPanel3Layout.createSequentialGroup()
	                        .addGap(66, 66, 66)
	                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
	                            .addGroup(jPanel3Layout.createSequentialGroup()
	                                .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)
	                                .addGap(18, 18, 18)
	                                .addComponent(jTextField10, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
	                            .addGroup(jPanel3Layout.createSequentialGroup()
	                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
	                                    .addComponent(jButton4, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
	                                    .addComponent(jCheckBox3, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
	                                    .addComponent(jLabel9, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
	                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
	                                    .addGroup(jPanel3Layout.createSequentialGroup()
	                                        .addGap(20, 20, 20)
	                                        .addComponent(jButton5))
	                                    .addGroup(jPanel3Layout.createSequentialGroup()
	                                        .addGap(28, 28, 28)
	                                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
	                                            .addGroup(jPanel3Layout.createSequentialGroup()
	                                                .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
	                                                .addGap(12, 12, 12)
	                                                .addComponent(jTextField9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
	                                            .addComponent(jComboBox3, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))))
	                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
	                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
	                                    .addGroup(jPanel3Layout.createSequentialGroup()
	                                        .addGap(38, 38, 38)
	                                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
	                                            .addGroup(jPanel3Layout.createSequentialGroup()
	                                                .addComponent(jLabel10, javax.swing.GroupLayout.DEFAULT_SIZE, 100, Short.MAX_VALUE)
	                                                .addGap(26, 26, 26)
	                                                .addComponent(jTextField7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
	                                            .addGroup(jPanel3Layout.createSequentialGroup()
	                                                .addComponent(jLabel12, javax.swing.GroupLayout.DEFAULT_SIZE, 86, Short.MAX_VALUE)
	                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
	                                                .addComponent(jTextField8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
	                                                .addGap(77, 77, 77)))
	                                        .addGap(253, 253, 253))
	                                    .addGroup(jPanel3Layout.createSequentialGroup()
	                                        .addGap(18, 18, 18)
	                                        .addComponent(jButton6)))))))
	                .addContainerGap())
	        );

	        jPanel3Layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {jButton4, jButton5});

	        jPanel3Layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {jLabel10, jTextField7});

	        jPanel3Layout.setVerticalGroup(
	            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
	            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
	                .addGap(24, 24, 24)
	                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
	                    .addComponent(jLabel9, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
	                    .addComponent(jComboBox3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
	                    .addComponent(jLabel10, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
	                    .addComponent(jTextField7, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
	                .addGap(27, 27, 27)
	                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
	                    .addComponent(jCheckBox3, javax.swing.GroupLayout.Alignment.TRAILING)
	                    .addComponent(jLabel11, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
	                    .addComponent(jTextField9, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
	                    .addComponent(jLabel12, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
	                    .addComponent(jTextField8, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
	                .addGap(42, 42, 42)
	                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
	                    .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
	                    .addComponent(jTextField10, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
	                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 47, Short.MAX_VALUE)
	                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
	                    .addComponent(jButton4, javax.swing.GroupLayout.Alignment.TRAILING)
	                    .addComponent(jButton5, javax.swing.GroupLayout.Alignment.TRAILING)
	                    .addComponent(jButton6, javax.swing.GroupLayout.Alignment.TRAILING))
	                .addGap(18, 18, 18)
	                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 217, javax.swing.GroupLayout.PREFERRED_SIZE)
	                .addContainerGap())
	        );

	        jPanel3Layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {jComboBox3, jLabel9});

	        jPanel3Layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {jButton4, jButton5});

	        jPanel3Layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {jLabel10, jTextField7, jTextField8, jTextField9});

	        jTabbedPane1.addTab("CurrencyPair", jPanel3);

	        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
	        jPanel1.setLayout(jPanel1Layout);
	        jPanel1Layout.setHorizontalGroup(
	            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
	            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
	                .addContainerGap()
	                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 52, Short.MAX_VALUE)
	                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
	                .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 670, javax.swing.GroupLayout.PREFERRED_SIZE))
	        );
	        jPanel1Layout.setVerticalGroup(
	            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
	            .addGroup(jPanel1Layout.createSequentialGroup()
	                .addContainerGap()
	                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
	                    .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.LEADING)
	                    .addComponent(jTabbedPane1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 512, Short.MAX_VALUE))
	                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
	        );

	        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
	      //  getContentPane().setLayout(layout);
	        layout.setHorizontalGroup(
	            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
	            .addGroup(layout.createSequentialGroup()
	                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
	                .addContainerGap(34, Short.MAX_VALUE))
	        );
	        layout.setVerticalGroup(
	            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
	            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
	        );

	     //   pack();
	    }// </editor-fold>

	private void jCheckBox1ActionPerformed(java.awt.event.ActionEvent evt) {                                           
	// TODO add your handling code here:
	}                                          

	private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {                                         
	// TODO add your handling code here:
	}                                        

	private void jCheckBox3ActionPerformed(java.awt.event.ActionEvent evt) {
	// TODO add your handling code here:
	}

	private void jTextField10ActionPerformed(java.awt.event.ActionEvent evt) {
	// TODO add your handling code here:
	}
	 private void getCurrencyDefaultData(DefaultTableModel model,DefaultComboBoxModel cmodel) {
	    	// TODO Auto-generated method stub
	    	Vector vector;
	    	try {
	    		currencyDefaultData.clear();
	    		
	    		vector = (Vector) remoteBORef.selectALLCurrencyDefault();
	    		Iterator it = vector.iterator();
	        	int i =0;
	    	while(it.hasNext()) {
	    		
	    		CurrencyDefault cp = (CurrencyDefault) it.next();
	    	
	    		model.insertRow(i, new Object[]{cp.getCurrency_code()});
	    		cmodel.insertElementAt(cp.getCountry(), i);
	    		primcurrency.insertElementAt(cp.getCurrency_code(), i);
	    		currencyDefaultData.put(i, cp);
	    		i++;
	    	}
	    	}
	    	catch (RemoteException e) {
	    		// TODO Auto-generated catch block
	    		e.printStackTrace();
	    	}
	    	
	    	
	    	
	    }
	 private void processTableData(DefaultTableModel model,String currency) {
			// TODO Auto-generated method stub
	    	Vector vector;
			try {
				
				
				vector = (Vector) remoteBORef.selectALLCurrencyPair(currency);
				Iterator it = vector.iterator();
		    	int i =0;
	    	while(it.hasNext()) {
	    		
	    		CurrencyPair cp = (CurrencyPair) it.next();
	    	
	    		model.insertRow(i,new Object[]{cp.getPrimary_currency(),cp.getQuoting_currency(),cp.getPair_pos_ref_b(),cp.getBp_factor(),cp.getQuote_factor(),cp.getSpot_days() });
	    	
	    	}
			}
	    	catch (RemoteException e) {
				// TODO Auto-generated catch block
				e.printStackTrace();
			}
	    	
	    	
			
		}
	 private String []  getCurrencys(Hashtable v) {
	    	String name [] = null;
	    	int i=0;
	    	if(v != null ) {
	    		name = new String[v.size()];
	    		Enumeration<CurrencyDefault> its = v.elements();
	    		while(its.hasMoreElements()) {
	    			name [i] = ( (CurrencyDefault) its.nextElement()).getCurrency_code();
	    			i++;
	    		}
	    	}
			return name;                                           
	        // TODO add your handling code here:
	    } 
	  
	    // Variables declaration - do not modify
	    private javax.swing.JButton jButton1;
	    private javax.swing.JButton jButton2;
	    private javax.swing.JButton jButton3;
	    private javax.swing.JButton jButton4;
	    private javax.swing.JButton jButton5;
	    private javax.swing.JButton jButton6;
	    private javax.swing.JCheckBox jCheckBox1;
	    private javax.swing.JCheckBox jCheckBox2;
	    private javax.swing.JCheckBox jCheckBox3;
	    private javax.swing.JComboBox jComboBox1;
	    private javax.swing.JComboBox jComboBox2;
	    private javax.swing.JComboBox jComboBox3;
	    private javax.swing.JLabel jLabel1;
	    private javax.swing.JLabel jLabel10;
	    private javax.swing.JLabel jLabel11;
	    private javax.swing.JLabel jLabel12;
	    private javax.swing.JLabel jLabel13;
	    private javax.swing.JLabel jLabel2;
	    private javax.swing.JLabel jLabel3;
	    private javax.swing.JLabel jLabel4;
	    private javax.swing.JLabel jLabel5;
	    private javax.swing.JLabel jLabel6;
	    private javax.swing.JLabel jLabel7;
	    private javax.swing.JLabel jLabel8;
	    private javax.swing.JLabel jLabel9;
	    private javax.swing.JPanel jPanel1;
	    private javax.swing.JPanel jPanel2;
	    private javax.swing.JPanel jPanel3;
	    private javax.swing.JScrollPane jScrollPane1;
	    private javax.swing.JScrollPane jScrollPane2;
	    private javax.swing.JTabbedPane jTabbedPane1;
	    private javax.swing.JTable jTable1;
	    private javax.swing.JTable jTable2;
	    private javax.swing.JTextField jTextField1;
	    private javax.swing.JTextField jTextField10;
	    private javax.swing.JTextField jTextField2;
	    private javax.swing.JTextField jTextField3;
	    private javax.swing.JTextField jTextField4;
	    private javax.swing.JTextField jTextField5;
	    private javax.swing.JTextField jTextField6;
	    private javax.swing.JTextField jTextField7;
	    private javax.swing.JTextField jTextField8;
	    private javax.swing.JTextField jTextField9;
	    // End of variables declaration
	}
