package apps.window.staticwindow;

import java.awt.CheckboxGroup;
import java.awt.event.MouseEvent;
import java.rmi.RemoteException;
import java.text.SimpleDateFormat;
import java.util.Enumeration;
import java.util.Hashtable;
import java.util.Iterator;
import java.util.Vector;

import javax.swing.AbstractButton;
import javax.swing.ButtonGroup;
import javax.swing.DefaultComboBoxModel;
import javax.swing.DefaultListModel;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import com.standbysoft.component.date.swing.JDatePicker;
import beans.Holiday;

import util.commonUTIL;

import dsServices.RemoteReferenceData;
import dsServices.ServerConnectionUtil;

public class HolidayWindow extends javax.swing.JPanel {
	public static  ServerConnectionUtil de = null;
	RemoteReferenceData remoteBORef;
	DefaultTableModel tmodel = null;
	 javax.swing.DefaultComboBoxModel country = new javax.swing.DefaultComboBoxModel();
	 Hashtable holidayData = new Hashtable();
	 Hashtable weekDays = new Hashtable();
	 public DefaultListModel cmodList2 = new DefaultListModel();
	 
	 private com.standbysoft.component.date.swing.JDatePicker jDatePicker1;
	
    /** Creates new form Holiday */
    public HolidayWindow() {
        initComponents();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">
    private void initComponents() {
    	de =ServerConnectionUtil.connect("localhost", 1099,commonUTIL.getServerIP());
      	 try {
      		
      		 remoteBORef = (RemoteReferenceData) de.getRMIService("ReferenceData");
      	//	Vector allholidays =  (Vector) remoteBORef.selectALLHolidays();
   			
   		//System.out.println(remoteBORef);
   	
      	 } catch (RemoteException e) {
   			// TODO Auto-generated catch block
   			commonUTIL.displayError(this.getName(), "initComponents", e);
   	}
        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        final ButtonGroup group = new ButtonGroup();

        jComboBox1 = new javax.swing.JComboBox();
        jLabel1 = new javax.swing.JLabel();
        jCheckBox1 = new javax.swing.JCheckBox();
        jCheckBox2 = new javax.swing.JCheckBox();
        jCheckBox3 = new javax.swing.JCheckBox();
        jCheckBox4 = new javax.swing.JCheckBox();
        jCheckBox5 = new javax.swing.JCheckBox();
        jCheckBox6 = new javax.swing.JCheckBox();
        jCheckBox7 = new javax.swing.JCheckBox();
        jScrollPane2 = new javax.swing.JScrollPane();
       jComboBox1.setEditable(false);
        jList1 = new javax.swing.JList();
        jLabel2 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();
        jDatePicker1 = new com.standbysoft.component.date.swing.JDatePicker();
        jDatePicker1.setDateFormat(commonUTIL.getDateFormat());
        jDatePicker1.setSelectedDate(commonUTIL.getCurrentDate()); 
       
        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("HolidayCode"));
        
     //  jDatePicker1.
      //  setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        String col[] = {"Currency"};
        tmodel = new DefaultTableModel(col,0);
        jTable1.setModel(tmodel);
        jScrollPane1.setViewportView(jTable1);
        getHolidayData(tmodel,country);
        jComboBox1.setModel(country);

        jLabel1.setText("COUNTRY");
               jCheckBox1.setText("MON");
        jCheckBox1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
            //    jCheckBox1ActionPerformed(evt);
            	if(jCheckBox1.isSelected()) {
                	weekDays.put("MON", "2");
                } else {
                	if(weekDays.contains("2"))  {
                		weekDays.remove("MON");
                	}
                }System.out.println(weekDays.size());
            }
        });

        jCheckBox2.setText("TUE");
        jCheckBox2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
               // jCheckBox2ActionPerformed(evt);
            	if(jCheckBox2.isSelected()) {
                	weekDays.put("TUE", "3");
                } else {
                	if(weekDays.contains("3"))  {
                		weekDays.remove("TUE");
                	}
                }//System.out.println(weekDays.size());
            }
        });

        jCheckBox3.setText("WED");
        jCheckBox3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
             //   jCheckBox3ActionPerformed(evt);
            	if(jCheckBox3.isSelected()) {
                	weekDays.put("WED", "4");
                } else {
                	if(weekDays.contains("4"))  {
                		weekDays.remove("WED");
                	}
                }
            //	System.out.println(weekDays.size());
            }
        });

        jCheckBox4.setText("THU");
        jCheckBox4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBox4ActionPerformed(evt);
                if(jCheckBox4.isSelected()) {
                	weekDays.put("THU", "5");
                } else {
                	if(weekDays.contains("5"))  {
                		weekDays.remove("THU");
                	}
                }
               // System.out.println(weekDays.size());
            }
            
        });

        jCheckBox5.setText("FRI");
        jCheckBox5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
               // jCheckBox5ActionPerformed(evt);
            	 if(jCheckBox5.isSelected()) {
                 	weekDays.put("FRI", "6");
                 } else {
                 	if(weekDays.contains("6"))  {
                 		weekDays.remove("FRI");
                 	}
                 }
            	// System.out.println(weekDays.size());
            }
        });

        jCheckBox6.setText("SAT");
        jCheckBox6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
               // jCheckBox6ActionPerformed(evt);
            	if(jCheckBox6.isSelected()) {
                	weekDays.put("SAT", "7");
                } else {
                	if(weekDays.contains("7"))  {
                		weekDays.remove("SAT");
                	}
                }
            //	System.out.println(weekDays.size());
            }
        });

        jCheckBox7.setText("SUN");
        jCheckBox7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
              //  jCheckBox7ActionPerformed(evt);
                if(jCheckBox7.isSelected()) {
                	weekDays.put("SUN", "1");
                } else {
                	if(weekDays.contains("1"))  {
                		weekDays.remove("SUN");
                	}
                }
            }
        });

        jList1.setModel(cmodList2);
        jScrollPane2.setViewportView(jList1);

        jLabel2.setText("Date");

        jButton1.setText("Date");

        jButton2.setText("ADD");

        jButton3.setText("DELETE");

        jButton4.setText("SAVE");

        jButton5.setText("EDIT");

        jButton6.setText("REMOVE");
        
        jTable1.addMouseListener(new java.awt.event.MouseAdapter() {

			@Override
			public void mouseClicked(MouseEvent e) {
				int rowindex = jTable1.getSelectedRow(); 
				
			   jComboBox1.setSelectedIndex(rowindex);
			   Holiday holi = new Holiday();
			   jCheckBox1.setSelected(false);
			   jCheckBox2.setSelected(false);
			   jCheckBox3.setSelected(false);
			   jCheckBox4.setSelected(false);
			   jCheckBox5.setSelected(false);
			   jCheckBox6.setSelected(false);
			   jCheckBox7.setSelected(false);
			   
			   weekDays.clear();
			   cmodList2.removeAllElements();
			   jList1.removeAll();
			   holi.setCurrency(jTable1.getValueAt(rowindex, 0).toString());
               try {
            	   holi = (Holiday) remoteBORef.selectHoliday(holi);
            	   if(holi.getHdate() != null) {
            		 String dates [] =   holi.getHdate().split(",");
            		 cmodList2.removeAllElements();
            		 for(int i=0;i<dates.length;i++) {
            			    cmodList2.add(i, dates[i]);
            		 }
            		 jList1.removeAll();
            		 jList1.setModel(cmodList2);
            	   }
            	   if(holi.getFweekday() == 2 || holi.getSweekdday() == 2) 
            		   jCheckBox1.setSelected(true);
            	   if(holi.getFweekday() == 3 || holi.getSweekdday() == 3) 
            		   jCheckBox2.setSelected(true);
            	   if(holi.getFweekday() == 4 || holi.getSweekdday() == 4) 
            		   jCheckBox3.setSelected(true);
            	   if(holi.getFweekday() == 5 || holi.getSweekdday() == 5) 
            		   jCheckBox4.setSelected(true);
            	   if(holi.getFweekday() == 6 || holi.getSweekdday() == 6) 
            		   jCheckBox5.setSelected(true);
            	   if(holi.getFweekday() == 7 || holi.getSweekdday() == 7) 
            		   jCheckBox6.setSelected(true);
            	   if(holi.getFweekday() == 1 || holi.getSweekdday() == 1) 
            		   jCheckBox7.setSelected(true);
            	   
            	   
			} catch (RemoteException e1) {
				// TODO Auto-generated catch block
				e1.printStackTrace();
			}
			
			}
        	
        });
        
        jButton2.addMouseListener(new java.awt.event.MouseAdapter() {

			@Override
			public void mouseClicked(MouseEvent e) {
				System.out.println(cmodList2.getSize() + " " + jDatePicker1.getSelectedDateAsText());
				
				if(cmodList2.getSize() > 0) {
					if(!cmodList2.contains(jDatePicker1.getSelectedDateAsText())) {
				            cmodList2.add(cmodList2.getSize(), jDatePicker1.getSelectedDateAsText());
					}
				}	else  {
					cmodList2.add(0, jDatePicker1.getSelectedDateAsText()); 
				}
				

			
			}
        	
        });
        jButton4.addMouseListener(new java.awt.event.MouseAdapter() {

			@Override
			public void mouseClicked(MouseEvent e) {
				
				System.out.println(weekDays.size());
				if(weekDays.size() > 2) {
		            		JOptionPane.showMessageDialog(null,"Select Only 2 days for Weekend ",null,
		    	      				JOptionPane.INFORMATION_MESSAGE);
		            		return;
				}
				if(jComboBox1.getSelectedIndex() <0) {
					JOptionPane.showMessageDialog(null,"Select Currency & Country ",null,
    	      				JOptionPane.INFORMATION_MESSAGE);
            		return;
				}
				Holiday holi = new Holiday();
				holi.setCountry(jComboBox1.getSelectedItem().toString());
				holi.setCurrency(tmodel.getValueAt(jTable1.getSelectedRow(), 0).toString());
				String dates = "";
				if(cmodList2.getSize() > 0) {
					for(int i=0;i<cmodList2.getSize();i++) {
						dates = dates + (String) cmodList2.get(i) + ",";
					}
					holi.setHdate(dates.substring(0, dates.length()-1));
				}
				
			
				Enumeration enu = weekDays.elements();
				int i = 0;
				while(enu.hasMoreElements()) {
					int temp =0;
					String le = (String) enu.nextElement();
		            if(i ==0 ) {
		            	
		            	holi.setFweekday(new Integer(le).intValue());
		            	i++;
		            } else {
		            	temp = new Integer(le).intValue();
		            	if(temp > holi.getFweekday()) {
		            	   holi.setSweekdday(temp);
		            	} else {
		            		 holi.setSweekdday(holi.getFweekday());
		            		 holi.setFweekday(temp);
		            	}
		            }
		         
				}
      try {
		remoteBORef.saveHoliday(holi);
	} catch (RemoteException e1) {
		// TODO Auto-generated catch block
		e1.printStackTrace();
	}
			
			}
        	
        });
        
        jButton6.addMouseListener(new java.awt.event.MouseAdapter() {

			@Override
			public void mouseClicked(MouseEvent e) {
				cmodList2.remove(jList1.getSelectedIndex());
				jList1.removeAll();
				jList1.setModel(cmodList2);
			}
        	
        });
        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(34, 34, 34)
                        .addComponent(jButton3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton5))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jCheckBox1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(4, 4, 4)
                                .addComponent(jCheckBox2)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jCheckBox3)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jCheckBox4)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jCheckBox5)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jCheckBox6)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jCheckBox7))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jComboBox1, 0, 291, Short.MAX_VALUE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jDatePicker1, javax.swing.GroupLayout.PREFERRED_SIZE, 176, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jButton2)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jButton6)))))
                .addGap(52, 52, 52))
        );

        jPanel1Layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {jCheckBox1, jCheckBox2, jCheckBox3, jCheckBox4, jCheckBox5, jCheckBox6, jCheckBox7});

        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 17, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(11, 11, 11)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jCheckBox1, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jCheckBox5, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jCheckBox6, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jCheckBox7, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jCheckBox4, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jCheckBox3, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jCheckBox2, javax.swing.GroupLayout.Alignment.TRAILING))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jDatePicker1)
                        .addComponent(jButton2)
                        .addComponent(jButton6))
                    .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 218, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jButton3)
                            .addComponent(jButton4)
                            .addComponent(jButton5))
                        .addGap(41, 41, 41))))
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 335, Short.MAX_VALUE)
        );

        jPanel1Layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {jComboBox1, jLabel1});

        jPanel1Layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {jCheckBox1, jCheckBox2, jCheckBox3, jCheckBox4, jCheckBox5, jCheckBox6, jCheckBox7});

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
     //   getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );


       // pack();
    }// </editor-fold>

private void jCheckBox1ActionPerformed(java.awt.event.ActionEvent evt) {                                           
// TODO add your handling code here:
}                                          

private void jCheckBox2ActionPerformed(java.awt.event.ActionEvent evt) {                                           
// TODO add your handling code here:
}                                          

private void jCheckBox3ActionPerformed(java.awt.event.ActionEvent evt) {                                           
// TODO add your handling code here:
}                                          

private void jCheckBox4ActionPerformed(java.awt.event.ActionEvent evt) {                                           
// TODO add your handling code here:
}                                          

private void jCheckBox5ActionPerformed(java.awt.event.ActionEvent evt) {                                           
// TODO add your handling code here:
}                                          

private void jCheckBox6ActionPerformed(java.awt.event.ActionEvent evt) {                                           
// TODO add your handling code here:
}                                          

private void jCheckBox7ActionPerformed(java.awt.event.ActionEvent evt) {                                           
// TODO add your handling code here:
}                                          

private int getCountryName(String currency) {
	
	int id = 0;
	int i = 0;
		Enumeration enu = holidayData.elements();
		while(enu.hasMoreElements()) {
			
			Holiday le = (Holiday) enu.nextElement();
			if(le.getCurrency().equalsIgnoreCase(currency)) {
				id = i;
				break;
			}
			i++;
				
			
	}	 
	return id;
	
}

private void getHolidayData(DefaultTableModel model,DefaultComboBoxModel cmodel) {
	// TODO Auto-generated method stub
	Vector vector;
	try {
		holidayData.clear();
		
		vector = (Vector) remoteBORef.selectALLHolidays();
		Iterator it = vector.iterator();
    	int i =0;
	while(it.hasNext()) {
		
		Holiday holiday = (Holiday) it.next();
	
		model.insertRow(i, new Object[]{holiday.getCurrency()});
		cmodel.insertElementAt(holiday.getCountry(), i);
		holidayData.put(i, holiday);
		i++;
	}
	}
	catch (RemoteException e) {
		// TODO Auto-generated catch block
		e.printStackTrace();
	}
	
	
	
}

    /**
     * @param args the command line arguments
     */
   
    // Variables declaration - do not modify
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JCheckBox jCheckBox1;
    private javax.swing.JCheckBox jCheckBox2;
    private javax.swing.JCheckBox jCheckBox3;
    private javax.swing.JCheckBox jCheckBox4;
    private javax.swing.JCheckBox jCheckBox5;
    private javax.swing.JCheckBox jCheckBox6;
    private javax.swing.JCheckBox jCheckBox7;
    private javax.swing.JComboBox jComboBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JList jList1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTable1;
    // End of variables declaration
}
