package apps.window.utilwindow;

import java.awt.Color;
import java.awt.Component;
import java.awt.EventQueue;
import java.awt.Font;
import java.awt.Toolkit;
import java.net.URL;
import java.rmi.RemoteException;
import java.util.Enumeration;
import java.util.Iterator;
import java.util.Vector;

import javax.swing.JComponent;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.SwingUtilities;
import javax.swing.UIManager;


import util.commonUTIL;

import beans.StartUPData;
import beans.Users;

import dsServices.RemoteReferenceData;
import dsServices.ServerConnectionUtil;

import apps.window.tradewindow.JFrameMainApplication;

/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * NewJFrame3.java
 *
 * Created on 29 Mar, 2013, 1:05:30 AM
 */
/**
 *
 * @author MPankaj
 */
public class Login extends javax.swing.JDialog {

    /** Creates new form NewJFrame3 */
	public boolean displagflag = false;
	public static  ServerConnectionUtil de = null;
	RemoteReferenceData remoteBORef;
	static String username = "";
	JFrameMainApplication mainApp = null;
	public Login() {
        initComponents();
    }
    public void setFont(JComponent comp) {
    	int countComp = comp.getComponentCount();
    	for(int i=0;i< countComp;i++) {
    		if( comp.getComponent(i) instanceof JComponent) {
    		JComponent comp1 = (JComponent) comp.getComponent(i);
    		if(comp1.getComponentCount() > 0) {
    			comp1.setFont(Font.decode("SansSerif-11"));
    			comp1.setFont(new java.awt.Font("Verdana", 0, 11));
    			setFont(comp1);
    			
    		} else {
    			comp.setFont(new java.awt.Font("Verdana", 0, 11));
    		comp.setFont(Font.decode("SansSerif-11"));
    		}
    		}
    	}
    }
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">
    private void initComponents() {
    	//installLnF();
    	de =ServerConnectionUtil.connect("localhost", 1099,commonUTIL.getLocalHost());
    	if(de == null) {
    		JOptionPane.showMessageDialog(null,"Server not Started " ,null,
       				JOptionPane.INFORMATION_MESSAGE);
    		System.exit(0);
    	return;
    	}
    	 try {
    		 remoteBORef = (RemoteReferenceData) de.getRMIService("ReferenceData");
 			
 			System.out.println(remoteBORef);
 		} catch (RemoteException e) {
 			// TODO Auto-generated catch block
 			e.printStackTrace();
 		}
        jPanel1 = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JPasswordField();
        jTextField2 = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jButton1.setFont(Font.decode("SansSerif-11"));
        jButton2.setFont(Font.decode("SansSerif-11"));
        jLabel1.setFont(Font.decode("SansSerif-11"));
        jLabel2.setFont(Font.decode("SansSerif-11"));
        jTextField2.setFont(Font.decode("SansSerif-11"));
       // jTextField2.set
        jLabel3.setFont(Font.decode("SansSerif-11"));
        jTextField1.setFont(Font.decode("SansSerif-11"));
        
        
        
        
        
     //   setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        jPanel1.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jButton1.setText("Login");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
               dispose();
            }
        });
        jButton2.setText("Cancel");

        jLabel1.setText("USERNAME");

        jLabel2.setText("PASSWORD");

        jTextField1.setText("user1");

        jTextField2.setText("user1");

        jLabel3.setText("Group");

Vector v1 =null;
        
		try {
			v1 = (Vector)	  remoteBORef.getStartUPData("UserGroup");
			
		} catch (RemoteException e) {
			// TODO Auto-generated catch block
			e.printStackTrace();
		}
		jComboBox1 = new javax.swing.JComboBox( convertVectortoSringArray(v1) );
		

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jButton1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 58, Short.MAX_VALUE)
                        .addComponent(jButton2))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(2, 2, 2)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, 63, Short.MAX_VALUE)
                            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 63, Short.MAX_VALUE)
                            .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, 63, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jComboBox1, 0, 127, Short.MAX_VALUE)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(jTextField2, javax.swing.GroupLayout.DEFAULT_SIZE, 127, Short.MAX_VALUE)
                                .addComponent(jTextField1, javax.swing.GroupLayout.DEFAULT_SIZE, 127, Short.MAX_VALUE)))))
                .addGap(4, 4, 4))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, 54, Short.MAX_VALUE)
                            .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED))
                    .addComponent(jTextField2, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(7, 7, 7)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton2)
                    .addComponent(jButton1))
                .addGap(7, 7, 7))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(12, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );


        setFont(this.getRootPane());
    //    pack();
    }// </editor-fold>
    
    private static void setDefaultFont() {      
    	Enumeration keys = UIManager.getDefaults().keys();      
    	while (keys.hasMoreElements()) {             
    		Object key = keys.nextElement();         
    		Object value = UIManager.get(key);        
    		if (value instanceof javax.swing.plaf.FontUIResource) {         
    			UIManager.put(key, new javax.swing.plaf.FontUIResource("Serif",Font.ITALIC,12));            
    			}         }     }
    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {
    	displagflag = true;
    	Users user = new Users();
    	user.setUser_groups(jComboBox1.getSelectedItem().toString());
    	System.out.println(jTextField1.getText());
    	System.out.println(jTextField2.getText());
    	user.setUser_name(jTextField2.getText());
    	user.setPassword(jTextField1.getText());
     try {
    	
    	user = remoteBORef.validateUser(user);
    	
		//user = remoteBORef.selectUser(user, user.getUser_groups());
		username = user.getUser_name();
	} catch (RemoteException e) {
		// TODO Auto-generated catch block
		e.printStackTrace();
	}
	if(user == null) {
		
		JOptionPane.showMessageDialog(null,"Login Failed" ,null,
   				JOptionPane.INFORMATION_MESSAGE);
	} else {
		mainApp = new JFrameMainApplication(user);
//mainApp.setBackground(commonUTIL.getColors());
		setFrame(mainApp, 500, 100); 
		
	   this.dispose();
    	} 
    }
    
    
    public static void installLnF() {
   	 EventQueue.invokeLater(new Runnable() {
   		 @Override
            public void run() {


           	 	try {
   	//	String lnfClassname = PREFERRED_LOOK_AND_FEEL;
   			
   			UIManager.setLookAndFeel(UIManager.getSystemLookAndFeelClassName());

   		//	UIManager.put("MenuBar.background", Color.RED);
   		//	UIManager.put("Menu.background", Color.GREEN);
         //  	UIManager.put("MenuItem.background", Color.MAGENTA);

           	 	} catch (Exception e) {
           	 	//	System.err.println("Cannot install " + PREFERRED_LOOK_AND_FEEL 				+ " on this platform:" + e.getMessage());
   	}
   		 }
   	 } );
   	


   }
    	public  void stop() {
    		if(mainApp != null)
    		mainApp.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE); 
    	}
    // TODO add your handling code here:

    public static void    setFrame(final JFrame frame, final int width, final int height) {   
    	SwingUtilities.invokeLater(new Runnable() {  
    		public void run() {  
    			frame.setTitle(" Cosmos Main Apps User: " + username);
    			URL imgURL =  imgURL = this.getClass().getResource("/resources/icon/sql.jpg");
    			frame.setIconImage(Toolkit.getDefaultToolkit()
    		      		   .getImage(imgURL));
    		//	frame.setIconImage(Toolkit.getDefaultToolkit()
    	      //		   .getImage("E:\\eclipse\\workspace\\sbiCCIL\\resources\\icon\\sql.jpg"));
    			//frame.setTitle(frame.getClass().getSimpleName());     
    			frame.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);   
    			frame.setSize(width, height);    
    			frame.setVisible(true);  
    			} });
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
    	
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
        	
            public void run() {
            	Login login = new Login();
            	//login.setTitle(title);
                new Login().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JComboBox jComboBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    
    private String []  convertVectortoSringArray(Vector v) {
    	String name [] = null;
    	int i=0;
    	if(v != null ) {
    		name = new String[v.size()];
    		Iterator its = v.iterator();
    		while(its.hasNext()) {
    			name [i] = ( (StartUPData) its.next()).getName();
    			i++;
    		}
    	}
		return name;                                           
        // TODO add your handling code here:
    } 
    // End of variables declaration
}
